// <auto-generated />
using System;
using GrowSeeds.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrowSeeds.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrowSeeds.Web.Data.Entities.PlantData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastFeeding")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastWater")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlantDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlantMedium")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("PlantStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDatabaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserDatabaseId");

                    b.ToTable("PlantsData");
                });

            modelBuilder.Entity("GrowSeeds.Web.Data.Entities.StrainDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cbd")
                        .HasColumnType("int");

                    b.Property<string>("Effects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flavor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int?>("PlantDataId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Thc")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserDatabaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantDataId");

                    b.HasIndex("UserDatabaseId");

                    b.ToTable("StrainsDatabase");
                });

            modelBuilder.Entity("GrowSeeds.Web.Data.Entities.UserDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersDatabase");
                });

            modelBuilder.Entity("GrowSeeds.Web.Data.Entities.PlantData", b =>
                {
                    b.HasOne("GrowSeeds.Web.Data.Entities.UserDatabase", null)
                        .WithMany("Plants")
                        .HasForeignKey("UserDatabaseId");
                });

            modelBuilder.Entity("GrowSeeds.Web.Data.Entities.StrainDatabase", b =>
                {
                    b.HasOne("GrowSeeds.Web.Data.Entities.PlantData", null)
                        .WithMany("Strains")
                        .HasForeignKey("PlantDataId");

                    b.HasOne("GrowSeeds.Web.Data.Entities.UserDatabase", null)
                        .WithMany("Strains")
                        .HasForeignKey("UserDatabaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
